name: CI Test

on:
    push:
        branches: [ main ]
    issue_comment:
        types: [ created ]
    workflow_dispatch: ~

jobs:
    build:
        if: github.event_name != 'issue_comment' || (github.event.issue.pull_request && github.event.comment.body == 'run-ci')


        env:
            GITHUB_DATA: ${{ toJSON(github) }}

        runs-on: ubuntu-latest

        steps:

            -   name: Get PR branch
                if: github.event_name == 'issue_comment'
                uses: xt0rted/pull-request-comment-branch@v3
                id: comment-branch

            -   name: Set latest commit status as pending
                if: github.event_name != 'push'
                uses: myrotvorets/set-commit-status-action@master
                with:
                    sha: ${{ steps.comment-branch.outputs.head_sha || github.sha }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    status: pending


            -   name: Checkout Code
                uses: actions/checkout@v4
                with:
                    ref: ${{ steps.comment-branch.outputs.head_ref || github.ref }}


            -   name: Job
                run: echo "$GITHUB_DATA"

            -   name: Set latest commit status
                uses: myrotvorets/set-commit-status-action@master
                if: github.event_name != 'push' && always()
                with:
                    sha: ${{ steps.comment-branch.outputs.head_sha || github.sha }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    status: ${{ job.status }}
