name: CI Test

on:
    push:
        branches: [ main ]
    issue_comment:
        types: [ created ]
    workflow_dispatch: ~

jobs:
    build:
        if: ${{ ! github.event.issue || (github.event.issue.pull_request && github.event.comment.body == 'run-ci') }}


        env:
            GITHUB_DATA: ${{ toJSON(github) }}
            IS_PULL_REQUEST: ${{ github.event.issue.pull_request && github.event.comment.body == 'run-ci' }}

        runs-on: ubuntu-latest

        steps:

            -   name: Get PR branch
                if: env.IS_PULL_REQUEST
                uses: xt0rted/pull-request-comment-branch@v3
                id: comment-branch

            -   name: Set PR latest commit status as pending
                if: env.IS_PULL_REQUEST
                uses: myrotvorets/set-commit-status-action@master
                with:
                    sha: ${{ steps.comment-branch.outputs.head_sha }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    status: pending


            -   name: Checkout Code
                uses: actions/checkout@v4
                with:
                    ref: ${{ steps.comment-branch.outputs.head_ref }}


            -   name: Job
                run: echo "$GITHUB_DATA"

            -   name: Set PR latest commit status
                uses: myrotvorets/set-commit-status-action@master
                if: env.IS_PULL_REQUEST && always()
                with:
                    sha: ${{ steps.comment-branch.outputs.head_sha }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    status: ${{ job.status }}
